//! The plugin manifest, `herdr-plugin.toml`, generated from code.
//!
//! The checked-in manifest is output of [`render`]; a test in `dashr-cli`
//! fails when the two disagree (requirement DASHR-HERDR-001). Generating it
//! means an action id, a pane id and the command that answers them cannot
//! drift apart.

use serde::Serialize;

pub const PLUGIN_ID: &str = "herdr-dashr";
pub const MIN_HERDR_VERSION: &str = "0.9.0";
/// The executable the build step installs, relative to the plugin root.
pub const BIN: &str = "bin/dashr";

/// The link-handler pattern for AWS CodePipeline console URLs, new
/// (`codesuite`) and old (`codepipeline/home`) consoles alike.
pub const PIPELINE_URL_PATTERN: &str = r"^https://([a-z0-9-]+\.)?console\.aws\.amazon\.com/(codesuite/codepipeline/pipelines/|codepipeline/home)";

#[derive(Debug, Serialize)]
struct Manifest {
    id: &'static str,
    name: &'static str,
    version: &'static str,
    min_herdr_version: &'static str,
    description: &'static str,
    platforms: Vec<&'static str>,
    build: Vec<Build>,
    startup: Vec<Hook>,
    actions: Vec<Action>,
    events: Vec<Event>,
    panes: Vec<Pane>,
    link_handlers: Vec<LinkHandler>,
}

#[derive(Debug, Serialize)]
struct Build {
    command: Vec<String>,
}

#[derive(Debug, Serialize)]
struct Hook {
    command: Vec<String>,
}

#[derive(Debug, Serialize)]
struct Action {
    id: &'static str,
    title: &'static str,
    contexts: Vec<&'static str>,
    command: Vec<String>,
}

#[derive(Debug, Serialize)]
struct Event {
    on: &'static str,
    command: Vec<String>,
}

#[derive(Debug, Serialize)]
struct Pane {
    id: &'static str,
    title: &'static str,
    placement: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    width: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    height: Option<&'static str>,
    command: Vec<String>,
}

#[derive(Debug, Serialize)]
struct LinkHandler {
    id: &'static str,
    title: &'static str,
    pattern: &'static str,
    action: &'static str,
}

fn dashr(args: &[&str]) -> Vec<String> {
    std::iter::once(BIN)
        .chain(args.iter().copied())
        .map(str::to_owned)
        .collect()
}

/// The actions the manifest declares: `(id, title)`.
pub const ACTIONS: &[(&str, &str)] = &[
    ("open", "Open live dashboard"),
    ("pipeline", "Open dashboard for a CodePipeline"),
    ("promote", "Promote dashboard to persistent Grafana"),
    ("doctor", "Check dashr prerequisites"),
];

/// The panes the manifest declares: `(id, title)`.
pub const PANES: &[(&str, &str)] = &[("dashboard", "dashr"), ("doctor", "dashr doctor")];

fn manifest(version: &'static str) -> Manifest {
    Manifest {
        id: PLUGIN_ID,
        name: "Herdr Dashr",
        version,
        min_herdr_version: MIN_HERDR_VERSION,
        description: "Agent-built, live Grafana dashboards in a Herdr pane, with masking between your data and the agent.",
        platforms: vec!["linux", "macos"],
        build: vec![
            Build {
                command: vec!["sh".into(), "scripts/install.sh".into()],
            },
            // Installs the dashboard-building skill for Claude Code; never
            // fails the install and never replaces a skill dashr did not
            // write (DASHR-SKILL-002).
            Build {
                command: dashr(&["skill", "install", "--best-effort"]),
            },
        ],
        startup: vec![Hook {
            command: dashr(&["herdr", "startup"]),
        }],
        actions: ACTIONS
            .iter()
            .map(|(id, title)| Action {
                id,
                title,
                contexts: vec!["workspace", "pane"],
                command: dashr(&["herdr", "action", id]),
            })
            .collect(),
        events: vec![Event {
            on: "pane.closed",
            command: dashr(&["herdr", "event", "pane-closed"]),
        }],
        panes: vec![
            Pane {
                id: "dashboard",
                title: "dashr",
                placement: "tab",
                width: None,
                height: None,
                command: dashr(&["herdr", "pane", "dashboard"]),
            },
            Pane {
                id: "doctor",
                title: "dashr doctor",
                placement: "popup",
                width: Some("80%"),
                height: Some("70%"),
                command: dashr(&["herdr", "pane", "doctor"]),
            },
        ],
        link_handlers: vec![LinkHandler {
            id: "codepipeline",
            title: "Open a live dashboard for this pipeline",
            pattern: PIPELINE_URL_PATTERN,
            action: "pipeline",
        }],
    }
}

const HEADER: &str = "\
# Generated by `dashr herdr manifest`. Do not edit by hand.
#
# The source of truth is `crates/dashr-herdr/src/manifest.rs`, and
# `crates/dashr-cli/tests/plugin_manifest.rs` fails if this file and that
# module disagree. Regenerate with:
#
#     cargo run --quiet --bin dashr -- herdr manifest > herdr-plugin.toml

";

/// The manifest text for `version`.
pub fn render(version: &'static str) -> String {
    let body = toml::to_string(&manifest(version)).expect("the manifest serializes");
    format!("{HEADER}{body}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_every_entrypoint() {
        let text = render("9.9.9");
        let parsed: toml::Value = toml::from_str(&text).expect("manifest is valid TOML");
        assert_eq!(parsed["id"].as_str(), Some(PLUGIN_ID));
        assert_eq!(parsed["version"].as_str(), Some("9.9.9"));
        assert_eq!(parsed["actions"].as_array().unwrap().len(), ACTIONS.len());
        assert_eq!(parsed["panes"].as_array().unwrap().len(), PANES.len());
        assert_eq!(parsed["events"][0]["on"].as_str(), Some("pane.closed"));
        assert_eq!(
            parsed["link_handlers"][0]["action"].as_str(),
            Some("pipeline")
        );
        assert!(text.starts_with("# Generated by"));
    }

    #[test]
    fn ids_follow_herdr_rules() {
        // Local ids: ASCII letters, digits, colon, underscore, hyphen; no dots.
        let ok = |id: &str| {
            !id.is_empty()
                && id
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || ":_-".contains(c))
        };
        for (id, _) in ACTIONS.iter().chain(PANES.iter()) {
            assert!(ok(id), "{id}");
        }
    }

    #[test]
    fn link_pattern_matches_both_consoles() {
        let pattern = regex::Regex::new(PIPELINE_URL_PATTERN).expect("pattern compiles");
        assert!(pattern.is_match(
            "https://eu-west-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/api-deploy/view?region=eu-west-1"
        ));
        assert!(pattern.is_match(
            "https://console.aws.amazon.com/codepipeline/home?region=us-east-1#/view/api"
        ));
        assert!(!pattern.is_match("https://github.com/x/y"));
        assert!(!pattern.is_match("https://evil.example/console.aws.amazon.com/codepipeline/home"));
    }
}
